Repository borglab/GTDynamics, pull requests merged in 2021-11, with the labels that each got.

#299 Eigen fixes
  examples/example_spider_walking/main.cpp
  gtdynamics/universal_robot/Joint.h
  gtdynamics/universal_robot/Link.h
  scripts/forward_dynamics_simple.cpp
Labels: bugfix

#300 Fix the regression value for testPneumaticFactors
  gtdynamics/jumpingrobot/tests/testPneumaticFactors.cpp
Labels: bugfix, quick review

#301 Feature/panda
  gtdynamics.i
  gtdynamics/universal_robot/sdf.cpp
  models/urdfs/panda/collision/finger.stl
  models/urdfs/panda/collision/hand.stl
  models/urdfs/panda/collision/link0.stl
  models/urdfs/panda/collision/link1.stl
  models/urdfs/panda/collision/link2.stl
  models/urdfs/panda/collision/link3.stl
  models/urdfs/panda/collision/link4.stl
  models/urdfs/panda/collision/link5.stl
  models/urdfs/panda/collision/link6.stl
  models/urdfs/panda/collision/link7.stl
  models/urdfs/panda/panda.urdf
  models/urdfs/panda/visual/finger.dae
  models/urdfs/panda/visual/hand.dae
  models/urdfs/panda/visual/link0.dae
  models/urdfs/panda/visual/link1.dae
  models/urdfs/panda/visual/link2.dae
  models/urdfs/panda/visual/link3.dae
  models/urdfs/panda/visual/link4.dae
  models/urdfs/panda/visual/link5.dae
  models/urdfs/panda/visual/link6.dae
  models/urdfs/panda/visual/link7.dae
  python/tests/test_forward_kinematics.py
  python/tests/test_panda.py
  python/tests/test_robot.py
Labels: quick review
