Repository borglab/GTDynamics, pull requests merged in 2021-09, with the labels that each got.

#262 Fixed subtle Eigen bug
  gtdynamics/utils/WalkCycle.cpp
  tests/testWalkCycle.cpp
Labels: bugfix

#268 Updated instructions for source install of SDFormat10
  README.md
Labels: docs

#263 Made Phase methods functional
  gtdynamics.i
  gtdynamics/utils/Phase.cpp
  gtdynamics/utils/Phase.h
  gtdynamics/utils/Trajectory.cpp
  gtdynamics/utils/WalkCycle.cpp
  gtdynamics/utils/WalkCycle.h
  tests/testPhase.cpp
  tests/testWalkCycle.cpp
Labels: refactor

#264 Detailed error check
  gtdynamics/config.h.in
  gtdynamics/factors/PointGoalFactor.cpp
  gtdynamics/universal_robot/Link.h
  gtdynamics/utils/Phase.cpp
  gtdynamics/utils/Trajectory.cpp
  tests/testSpiderWalking.cpp
  tests/testSpiderWalking.csv
Labels: testing

#275 Interpolation Test Fix
  tests/testInitializeSolutionUtils.cpp
Labels: bugfix

#273 Make link fixing for Robot functional
  examples/example_cart_pole_trajectory_optimization/main.cpp
  examples/example_inverted_pendulum_trajectory_optimization/inverted_pendulum.py
  examples/example_inverted_pendulum_trajectory_optimization/main.cpp
  gtdynamics.i
  gtdynamics/universal_robot/Joint.h
  gtdynamics/universal_robot/Link.h
  gtdynamics/universal_robot/Robot.cpp
  gtdynamics/universal_robot/Robot.h
  gtdynamics/universal_robot/RobotModels.h
  gtdynamics/universal_robot/sdf.cpp
  gtdynamics/utils/PointOnLink.h
  scripts/alejandro_yetong_01_id_four_bar.cpp
  scripts/forward_dynamics_simple.cpp
  scripts/stephanie01_ForwardDynamicsThreeLink.cpp
  tests/testDynamicsGraph.cpp
  tests/testInitializeSolutionUtils.cpp
  tests/testRobot.cpp
Labels: bugfix

#279 Refactor Joint Tests
  gtdynamics/universal_robot/ScrewJointBase.cpp
  tests/testRevoluteJoint.cpp
Labels: refactor

#277 Miscellaneous
  examples/example_jumping_robot/tests/test_jumping_robot.py
  gtdynamics.i
  python/tests/test_forward_kinematics.py
Labels: quick review

#284 Remove need for leading slash when loading robot models
  examples/example_cart_pole_trajectory_optimization/main.cpp
  examples/example_forward_dynamics/main.cpp
  examples/example_full_kinodynamic_balancing/main.cpp
  examples/example_full_kinodynamic_walking/main_rotate.cpp
  examples/example_full_kinodynamic_walking/main_walk_forward.cpp
  examples/example_inverted_pendulum_trajectory_optimization/main.cpp
  examples/example_quadruped_mp/main.cpp
  examples/example_spider_walking/main.cpp
  examples/example_spider_walking/main_rotate.cpp
  gtdynamics/config.h.in
  gtdynamics/universal_robot/RobotModels.h
  scripts/gerry00_ForwardDynamicsPrismatic.cpp
  scripts/stephanie02_spider_sdf.cpp
  tests/contactGoalsExample.h
  tests/testContactEqualityFactor.cpp
  tests/testDynamics.cpp
  tests/testDynamicsGraph.cpp
  tests/testForwardKinematicsFactor.cpp
  tests/testInitializeSolutionUtils.cpp
  tests/testObjectiveFactors.cpp
  tests/testPhase.cpp
  tests/testRobot.cpp
  tests/testSdf.cpp
  tests/testSpiderWalking.cpp
  tests/testStatics.cpp
  tests/testTrajectory.cpp
  tests/testWalkCycle.cpp
  tests/walkCycleExample.h
Labels: feature, refactor

#280 Joint Measurement Factor
  gtdynamics.i
  gtdynamics/factors/JointMeasurementFactor.h
  gtdynamics/factors/PoseFactor.h
  python/tests/test_factors.py
  tests/testJointMeasurementFactor.cpp
Labels: feature
