Repository borglab/GTDynamics, pull requests merged in 2021-12, with the labels that each got.

#312 Pose Factor Test
  gtdynamics.i
  gtdynamics/factors/PoseFactor.h
  python/tests/test_factors.py
  tests/testPoseFactor.cpp
Labels: question

#313 Move jumping robot python files to jumpingrobot directory
  gtdynamics/jumpingrobot/src/actuation_graph_builder.py
  gtdynamics/jumpingrobot/src/helpers.py
  gtdynamics/jumpingrobot/src/jr_graph_builder.py
  gtdynamics/jumpingrobot/src/jr_simulator.py
  gtdynamics/jumpingrobot/src/jr_values.py
  gtdynamics/jumpingrobot/src/jr_visualizer.py
  gtdynamics/jumpingrobot/src/jumping_robot.py
  gtdynamics/jumpingrobot/src/robot_graph_builder.py
  gtdynamics/jumpingrobot/src/test_jr_graph_builder.py
  gtdynamics/jumpingrobot/src/test_jr_simulator.py
  gtdynamics/jumpingrobot/src/test_jr_values.py
  gtdynamics/jumpingrobot/src/test_jumping_robot.py
  gtdynamics/jumpingrobot/yaml/robot_config.yaml
Labels: bugfix

#308 wrench factor with expressions
  gtdynamics.i
  gtdynamics/cablerobot/src/cdpr_planar.py
  gtdynamics/dynamics/Dynamics.h
  gtdynamics/dynamics/DynamicsGraph.cpp
  gtdynamics/factors/PoseFactor.h
  gtdynamics/factors/TorqueFactor.h
  gtdynamics/factors/TwistAccelFactor.h
  gtdynamics/factors/TwistFactor.h
  gtdynamics/factors/WrenchEquivalenceFactor.h
  gtdynamics/factors/WrenchFactor.cpp
  gtdynamics/factors/WrenchFactor.h
  gtdynamics/factors/WrenchPlanarFactor.h
  gtdynamics/statics/StaticsSlice.cpp
  gtdynamics/universal_robot/Joint.cpp
  gtdynamics/universal_robot/Joint.h
  gtdynamics/universal_robot/Link.cpp
  gtdynamics/universal_robot/Link.h
  gtdynamics/utils/JsonSaver.h
  tests/testPoseFactor.cpp
  tests/testTorqueFactor.cpp
  tests/testTwistAccelFactor.cpp
  tests/testTwistFactor.cpp
  tests/testWrenchEquivalenceFactor.cpp
  tests/testWrenchFactor.cpp
  tests/testWrenchPlanarFactor.cpp
Labels: feature

#314 Jumping Robot Python Tests
  .github/workflows/python-ci.yml
  gtdynamics/jumpingrobot/src/actuation_graph_builder.py
  gtdynamics/jumpingrobot/src/jr_graph_builder.py
  gtdynamics/jumpingrobot/src/jr_simulator.py
  gtdynamics/jumpingrobot/src/jr_values.py
  gtdynamics/jumpingrobot/src/jr_visualizer.py
  gtdynamics/jumpingrobot/src/jumping_robot.py
  gtdynamics/jumpingrobot/src/robot_graph_builder.py
  gtdynamics/jumpingrobot/src/test_jr_graph_builder.py
  gtdynamics/jumpingrobot/src/test_jr_simulator.py
  gtdynamics/jumpingrobot/src/test_jr_values.py
  gtdynamics/jumpingrobot/src/test_jumping_robot.py
  python/CMakeLists.txt
Labels: bugfix, ci

#315 enable 3 options for optimization
  gtdynamics.i
  gtdynamics/factors/PointGoalFactor.cpp
  gtdynamics/factors/PointGoalFactor.h
  gtdynamics/kinematics/Kinematics.h
  gtdynamics/kinematics/KinematicsInterval.cpp
  gtdynamics/kinematics/KinematicsSlice.cpp
  gtdynamics/kinematics/KinematicsTrajectory.cpp
  gtdynamics/optimizer/AugmentedLagrangianOptimizer.h
  gtdynamics/optimizer/ConstrainedOptimizer.h
  gtdynamics/optimizer/EqualityConstraint.h
  gtdynamics/optimizer/Optimizer.cpp
  gtdynamics/optimizer/Optimizer.h
  gtdynamics/optimizer/PenaltyMethodOptimizer.h
  gtdynamics/utils/Trajectory.h
  tests/testEqualityConstraint.cpp
  tests/testKinematicsInterval.cpp
  tests/testKinematicsSlice.cpp
  tests/testObjectiveFactors.cpp
  tests/testPhase.cpp
  tests/testPointGoalFactor.cpp
  tests/testTrajectory.cpp
  tests/testWalkCycle.cpp
Labels: feature

#321 WIP: Chain Class
  gtdynamics/dynamics/Chain.cpp
  gtdynamics/dynamics/Chain.h
  python/tests/prototype/chain.py
  tests/testChain.cpp
Labels: feature

#316 Robot Serialization
  .github/workflows/linux-ci.yml
  gtdynamics.i
  gtdynamics/statics/StaticsSlice.cpp
  gtdynamics/universal_robot/HelicalJoint.h
  gtdynamics/universal_robot/Joint.h
  gtdynamics/universal_robot/Link.h
  gtdynamics/universal_robot/PrismaticJoint.h
  gtdynamics/universal_robot/RevoluteJoint.h
  gtdynamics/universal_robot/Robot.h
  tests/testHelicalJoint.cpp
  tests/testLink.cpp
  tests/testPrismaticJoint.cpp
  tests/testRevoluteJoint.cpp
  tests/testRobot.cpp
Labels: feature

#323 Convert Optimizer Arguments from shared pointers to objects
  gtdynamics.i
  gtdynamics/kinematics/Kinematics.h
  gtdynamics/kinematics/KinematicsSlice.cpp
  gtdynamics/optimizer/AugmentedLagrangianOptimizer.cpp
  gtdynamics/optimizer/AugmentedLagrangianOptimizer.h
  gtdynamics/optimizer/Optimizer.cpp
  gtdynamics/optimizer/Optimizer.h
  gtdynamics/optimizer/PenaltyMethodOptimizer.cpp
  gtdynamics/optimizer/PenaltyMethodOptimizer.h
  gtdynamics/statics/Statics.h
  gtdynamics/statics/StaticsSlice.cpp
  tests/testKinematicsInterval.cpp
  tests/testKinematicsSlice.cpp
  tests/testStaticsSlice.cpp
Labels: refactor

#326 Various Fixes
  gtdynamics.i
  gtdynamics/factors/PoseFactor.h
  python/gtdynamics/preamble/cablerobot.h
  python/gtdynamics/preamble/gtdynamics.h
  python/gtdynamics/preamble/jumpingrobot.h
  python/gtdynamics/specializations/cablerobot.h
  python/gtdynamics/specializations/gtdynamics.h
  python/gtdynamics/specializations/jumpingrobot.h
  python/templates/gtdynamics.tpl
  python/tests/test_factors.py
  scripts/nithya00_constrained_opt_benchmark.cpp
Labels: refactor
