Repository borglab/GTDynamics, pull requests merged in 2022-01, with the labels that each got.

#322 add contact constraints
  gtdynamics.i
  gtdynamics/factors/ContactDynamicsMomentFactor.h
  gtdynamics/factors/ContactHeightFactor.h
  gtdynamics/factors/ContactKinematicsAccelFactor.h
  gtdynamics/factors/ContactKinematicsTwistFactor.h
  tests/testContactDynamicsMomentFactor.cpp
  tests/testContactHeightFactor.cpp
  tests/testContactKinematicsAccelFactor.cpp
  tests/testContactKinematicsTwistFactor.cpp
Labels: quick review

#327 Speedup Linux CI
  .github/workflows/linux-ci.yml
Labels: ci

#328 Remove `internal` namespace
  examples/example_cart_pole_trajectory_optimization/main.cpp
  examples/example_full_kinodynamic_balancing/main.cpp
  examples/example_full_kinodynamic_walking/main_rotate.cpp
  examples/example_full_kinodynamic_walking/main_walk_forward.cpp
  examples/example_inverted_pendulum_trajectory_optimization/inverted_pendulum.py
  examples/example_inverted_pendulum_trajectory_optimization/main.cpp
  examples/example_quadruped_mp/main.cpp
  examples/example_spider_walking/main_rotate.cpp
  gtdynamics.i
  gtdynamics/cablerobot/src/cdpr_planar.py
  gtdynamics/cablerobot/src/cdpr_planar_controller.py
  gtdynamics/cablerobot/src/test_cdpr_planar.py
  gtdynamics/cablerobot/tests/testCableLengthFactor.cpp
  gtdynamics/cablerobot/tests/testCableTensionFactor.cpp
  gtdynamics/cablerobot/tests/testCableVelocityFactor.cpp
  gtdynamics/dynamics/DynamicsGraph.cpp
  gtdynamics/factors/ContactEqualityFactor.h
  gtdynamics/factors/ContactPointFactor.h
  gtdynamics/factors/ForwardKinematicsFactor.h
  gtdynamics/factors/JointMeasurementFactor.h
  gtdynamics/factors/ObjectiveFactors.cpp
  gtdynamics/factors/ObjectiveFactors.h
  gtdynamics/factors/PoseFactor.h
  gtdynamics/factors/WrenchPlanarFactor.h
  gtdynamics/jumpingrobot/src/actuation_graph_builder.py
  gtdynamics/jumpingrobot/src/jr_simulator.py
  gtdynamics/jumpingrobot/src/jr_values.py
  gtdynamics/jumpingrobot/src/robot_graph_builder.py
  gtdynamics/kinematics/Kinematics.h
  gtdynamics/kinematics/KinematicsSlice.cpp
  gtdynamics/statics/StaticsSlice.cpp
  gtdynamics/universal_robot/Joint.cpp
  gtdynamics/universal_robot/Link.cpp
  gtdynamics/universal_robot/Robot.cpp
  gtdynamics/utils/Phase.h
  gtdynamics/utils/Trajectory.cpp
  gtdynamics/utils/Trajectory.h
  gtdynamics/utils/initialize_solution_utils.cpp
  gtdynamics/utils/values.cpp
  gtdynamics/utils/values.h
  python/tests/test_factors.py
  python/tests/test_forward_kinematics.py
  python/tests/test_four_bar.py
  python/tests/test_print.py
  scripts/alejandro_yetong_01_id_four_bar.cpp
  tests/testContactPointFactor.cpp
  tests/testDynamicsGraph.cpp
  tests/testForwardKinematicsFactor.cpp
  tests/testKinematicsInterval.cpp
  tests/testKinematicsSlice.cpp
  tests/testObjectiveFactors.cpp
  tests/testPoseFactor.cpp
  tests/testPreintegratedContactFactors.cpp
  tests/testStaticWrenchFactor.cpp
  tests/testTorqueFactor.cpp
  tests/testTwistAccelFactor.cpp
  tests/testTwistFactor.cpp
  tests/testWrenchEquivalenceFactor.cpp
  tests/testWrenchFactor.cpp
  tests/testWrenchPlanarFactor.cpp
Labels: refactor
